### ISSUE TITLE
Bug Error

### ISSUE THREAD

**Issue by Nai-mul** [TheFourGreatErrors/alpha-rptr#16]
when I tryed to start bot by command - python3 main.py --account binanceaccount1 --exchange binance --pair BTCUSDT --strategy Doten

Is showing callback error 

2021-06-14 14:31:28,628 - ERROR - error from callback <bound method BinanceFuturesWs.__on_message of <src.binance_futures_websocket.BinanceFuturesWs object at 0x762c2351c0>>: __on_message() missing 1 required positional argument: 'message'

**Comment by TheFourGreatErrors** [comment]
Hi, using older version of websocket-client==0.52.0 should work.

**Comment by Nai-mul** [comment]
Hi , after installation of websocket-client==0.52.0
raise WebSocketBadStatusException("Handshake status %d %s", status, status_message)
websocket._exceptions.WebSocketBadStatusException: Handshake status 502 Bad Gateway

**Comment by Nai-mul** [comment]
naimul@ubuntu:~/rptr$ python main.py --test --account binanceaccount1 --exchange binance --pair BTCUSDT --strategy OCC
Traceback (most recent call last):
  File "main.py", line 8, in <module>
    from src.factory import BotFactory
  File "/home/naimul/rptr/src/__init__.py", line 264
    def notify(message: object, fileName: object = None) -> object:
                      ^
SyntaxError: invalid syntax
naimul@ubuntu:~/rptr$ python3 main.py --test --account binanceaccount1 --exchange binance --pair BTCUSDT --strategy OCC
Traceback (most recent call last):
  File "main.py", line 8, in <module>
    from src.factory import BotFactory
  File "/home/naimul/rptr/src/__init__.py", line 13, in <module>
    import talib
  File "/home/naimul/.local/lib/python3.8/site-packages/talib/__init__.py", line 52, in <module>
    from ._ta_lib import (
  File "__init__.pxd", line 242, in init talib._ta_lib
ValueError: numpy.ndarray size changed, may indicate binary incompatibility. Expected 88 from C header, got 80 from PyObject

**Comment by praveenbm5** [comment]
Remove numpy and install again... this solved this error for me
